const superheroNames = {
    first: [
        "Agent",
        "Doctor",
        "Muscular",
        "Harass",
        "Professor",
        "Sturky",
        "Spicy",
        "Controlling",
        "Fast",
        "Growling",
        "Master",
        "Pumpy",
        "Tiny",
        "Maculine",
        "Feminine",
        "Protective",
        "Hungry",
        "Bald",
        "Orderly",
        "Hungry",
        "Gnarly",
    ],
    second: [
        "Citizen",
        "Harassment",
        "Toyboy",
        "Teacher",
        "Gangster",
        "Eagle",
        "Orange",
        "Father",
        "Mother",
        "Boy",
        "Girl",
        "Grandpa",
        "Grandma",
        "Lightning",
        "Darkness",
        "Survivor",
        "Postman",
        "Influencer",
        "Bacteria",
        "Bug",
        "Inspector",
    ],
};

export default superheroNames;
